#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Check staged files with Lint-Staged
yarn test && yarn lint-staged

# Update COMMITLOG
yarn commitlog

# Fix markdown
yarn hallmark

# Commit COMMITLOG
git add COMMITLOG.md
